repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: pretty-format-json
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.3
  hooks:
    - id: actionlint
- repo: local
  hooks:
  - id: ruff
    name: Ruff fix
    language: system
    entry: uv run ruff check --fix
    types: [python]
  - id: ruff-format
    name: Ruff format
    language: system
    types: [python]
    entry: uv run ruff format
- repo: local
  hooks:
  - id: mypy
    name: Run mypy
    language: system
    entry: uv run mypy
    types: [python]
